version: '3.8'

services:
  audit-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audit-server
    command: uvicorn audit_server:app --host 0.0.0.0 --port 9099 --reload
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "9099:9099"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/audit_db
    depends_on:
      - audit_db

  audit_db:
    image: postgres:14
    container_name: audit-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: audit_db
    ports:
      - "5532:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

